# Growbie configuration file

# growable plants, and max number of them to grow on adjacent tiles
growable_plants:
  RED_ROSE: 4
  YELLOW_FLOWER: 4
  PUMPKIN: 2
  RED_MUSHROOM: 2
  BROWN_MUSHROOM: 2
  LEAVES: 2
  
#chance of success, out of 100. 0 is always failure, 100 is always success.
growable_plants_success_chance:100

# growable blocks
# block type, and what it should convert into when fed bone meal
growable_blocks:
  DIRT: GRASS
  COBBLESTONE: MOSSY_COBBLESTONE
  LOG: LEAVES
  
#chance of success, out of 100. 0 is always failure, 100 is always success.
growable_blocks_success_chance:100
  
# spreadable blocks
# seed block, followed by what it can propagate to and clone itself
spreadable_blocks:
  GRASS: DIRT
  MOSSY_COBBLESTONE: COBBLESTONE
  
#chance of success, out of 100. 0 is always failure, 100 is always success.
spreadable_blocks_success_chance:100