name: Growbie
main: com.afforess.growbie.Growbie
version: 2.41
authors: [Afforess, Cyklo, UnixSystem]
description: A simple plugin that allows bonemeal to grow grass on dirt, spread pumpkins, and spread flowers